# {'scope':
#      {'type': 'websocket', 'path': '/ws/chat/test/', 'headers':
#          [(b'host', b'localhost:8000'),
#           (b'connection', b'Upgrade'),
#           (b'pragma', b'no-cache'),
#           (b'cache-control', b'no-cache'),
#           (b'user-agent', b'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'),
#           (b'upgrade', b'websocket'),
#           (b'origin', b'http://localhost:8000'),
#           (b'sec-websocket-version', b'13'),
#           (b'accept-encoding', b'gzip, deflate, br'),
#           (b'accept-language', b'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6'),
#           (b'cookie', b'csrftoken=TMwcQR6TuDK3TIMIMoGNTYIxSfYVqxbXMd5HnnovqdW4hGnFmzasRyoTobDtpWho; sessionid=6z494g5vycto5evudjwombuoa5mozd5d'),
#           (b'sec-websocket-key', b'YpEmWNOvG3KmGHbr4fOL/w=='),
#           (b'sec-websocket-extensions', b'permessage-deflate; client_max_window_bits')],
#       'query_string': b'', 'client': ['127.0.0.1', 60904], 'server': ['127.0.0.1', 8000], 'subprotocols': [],
#       'cookies': {'csrftoken': 'TMwcQR6TuDK3TIMIMoGNTYIxSfYVqxbXMd5HnnovqdW4hGnFmzasRyoTobDtpWho',
#                   'sessionid': '6z494g5vycto5evudjwombuoa5mozd5d'},
#       'session': <django.utils.functional.LazyObject object at 0x7f0d248e8780>,
#       'user': <channels.auth.UserLazyObject object at 0x7f0d248e87b8>,
#                                                 'path_remaining': '',
# 'url_route': {'args': (), 'kwargs': {'room_name': 'test'}}}, 'groups': [],
# 'channel_layer': <channels_redis.core.RedisChannelLayer object at 0x7f0d248db828>,
#                                                                   'channel_name': 'specific.BFcqaaae!nkvwOneVZyep',
# 'channel_receive': functools.partial(<bound method RedisChannelLayer.receive of <channels_redis.core.RedisChannelLayer object at 0x7f0d248db828>>, 'specific.BFcqaaae!nkvwOneVZyep'), 'base_send': <bound method SessionMiddlewareInstance.send of <channels.sessions.SessionMiddlewareInstance object at 0x7f0d248e8748>>, 'room_name': 'test', 'room_group_name': 'chat_test'}