# Generated by Django 2.1.3 on 2018-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is message read'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(verbose_name='User message'),
        ),
    ]
